const searchData = [
  "Gary February",
  "Alex Jäger",
  "Dominic Spike",
  "Alice Smith",
  "Senior Engineer",
  "Backend Team",
  "Java",
  "Spring Boot",
  "Microservices",
  "Leadership",
  "Communication",
  "Problem-Solving",
  "Project Apollo",
  "Project Zeus",
  "Bob Johnson",
  "Marketing Specialist",
  "Digital Marketing",
  "SEO",
  "Content Creation",
  "Google Analytics",
  "Creativity",
  "Strategic Thinking",
  "Collaboration",
  "Project Hermes",
  "Project Hera",
  "Carol Williams",
  "Sales Manager",
  "B2B Sales",
  "Negotiation",
  "CRM",
  "Lead Generation",
  "Persuasion",
  "Customer Service",
  "Networking",
  "Project Atlas",
  "Project Athena",
  "David Brown",
  "Support Agent",
  "Technical Support",
  "Troubleshooting",
  "Technical Writing",
  "Zendesk",
  "Empathy",
  "Patience",
  "Eva Martinez",
  "Financial Analyst",
  "Budgeting Team",
  "Financial Modeling",
  "Excel",
  "SQL",
  "Analytical Thinking",
  "Attention to Detail",
  "Project Mercury",
  "Project Orion",
  "Frank Miller",
  "Research Scientist",
  "AI Team",
  "Machine Learning",
  "Python",
  "Data Analysis",
  "Curiosity",
  "Innovation",
  "Critical Thinking",
  "Project Vega",
  "Project Sirius",
  "Grace Lee",
  "Junior Engineer",
  "Frontend Team",
  "JavaScript",
  "React",
  "CSS",
  "Teamwork",
  "Hank Green",
  "Senior Marketing Manager",
  "Branding Team",
  "Market Analysis",
  "Brand Management",
  "Campaign Planning",
  "Irene Black",
  "Sales Executive",
  "B2C Sales",
  "Salesforce",
  "Customer Relations",
  "Market Research",
  "Jack White",
  "Support Specialist",
  "Customer Care",
  "Kim Brown",
  "Accountant",
  "Financial Reporting",
  "Accounting",
  "SAP",
  "Liam Davis",
  "Data Scientist",
  "R",
  "Ryan Young",
  "Research Analyst",
  "Statistics",
  "Sara Hill",
  "Junior Developer",
  "HTML",
  "Tom Adams",
  "Marketing Coordinator",
  "Social Media",
  "Email Marketing",
  "Uma Brown",
  "Sales Assistant",
  "Vince Clark",
  "Support Technician",
  "Wendy Davis",
  "Data Analysis",
  "Xander Evans",
  "Data Analyst",
  "Data Visualization",
  "Paula Xavier",
  "Quincy Young",
  "Software Engineer",
  "Rebecca Zane",
  "Marketing Analyst",
  "Alan Harris",
  "Sales Consultant",
  "Bella Johnson",
  "Customer Support Specialist",
  "Charlie King",
  "Financial Planner",
  "Diana Lewis",
  "Research Associate",
  "Machine Learning",
  "Edward Martin",
  "Frontend Team",
  "Fiona Nelson",
  "Marketing Assistant",
  "George Owens",
  "Sales Manager",
  "Hannah Perez",
  "Support Lead",
  "Ian Quinn",
  "Senior Accountant",
  "Jane Roberts",
  "Data Scientist",
  "Kyle Smith",
  "C#",
  "ASP.NET",
  "Lisa Taylor",
  "Marketing Coordinator",
  "Michael Underwood",
  "Sales Associate",
  "Nora Vance",
  "Oliver Watson",
  "Financial Controller",
  "Budgeting",
  "Quincy Young",
  "Software Engineer",
  "Rebecca Zane",
  "Marketing Analyst",
  "Samuel Adams",
  "Tina Baker",
  "Uma Collins",
  "Violet Dean",
  "William Edwards",
  "Xena Foster",
];

export default searchData;
